#!/usr/bin/python3

import sys

from livefs_edit.context import EditContext
from livefs_edit import actions

isopath = sys.argv[1]
destpath = sys.argv[2]

ctxt = EditContext(isopath)
ctxt.mount_iso()

try:
    actions.add_debs_to_pool(ctxt, sys.argv[3:])
    actions.shell(ctxt)

    ctxt.repack_iso(destpath)
finally:
    ctxt.teardown()
