#!/usr/bin/python3

import os
import subprocess
import sys

from livefs_edit import tmp
from livefs_edit import iso

isopath = os.path.realpath(sys.argv[1])

tmp.setup()

iso.setup_iso(isopath)

subprocess.run(['/bin/bash'])
